### ISSUE TITLE
Get Published Blog by blog_id

### ISSUE THREAD

**Issue by daveaugustus** [the-monkeys/the_monkeys_engine#197]
1. **Existing Behavior:**
   - The API currently considers only the `is_draft` keyword.
   - When `is_draft` is `true`, it avoids fetching the blog.
   - When `is_draft` is `false`, it returns the blog.

2. **Proposed Enhancement:**
   - Introduce a new parameter called `is_archived`.
   - Define the behavior as follows:
     - When `is_archived` is `true`, leave the blog (i.e., do not fetch it).
     - When `is_archived` is `false`, return the blog.
     - When `is_archived` is not present, return the blog regardless of its archived status.

3. **Implementation:**
   - To implement this enhancement, you'll need to modify the API logic to handle the new `is_archived` parameter appropriately.

**File:** microservices/the_monkeys_blog/internal/database/opensearch.go
**Method:** GetPublishedBlogById

**Comment by Jacob613-chain** [comment]
jacob
